/***********************************************************************
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.
//******
// Filename:
// Description:
// Author:
// CreateTime:
/***********************************************************************/
package _const

const (
	//login
	ERR_NOT_LOGIN               = 10001
	ERR_USER_NOT_EXIST          = 10002
	ERR_LOGIN_SCENE_INVALID     = 10004
	ERR_LOGIN_FAILED            = 10005
	ERR_PASSWORD_INVLID         = 10080
	ERR_VERIFYCODE_INVLID       = 10081
	ERR_FIND_USER_ERROR         = 10006
	ERR_SCENE_PERMISSION_DENIED = 10007
	//createnewuser
	ERR_CREATE_USER_ERROR  = 10090
	ERR_USER_ALREADY_EXIST = 10091
	//getverifycode
	ERR_GETVCODE_ERROR                 = 10060
	ERR_GETVCODE_NEED_CAPTCHA          = 10061
	ERR_GETVCODE_CAPTCHA_VERIFY_FAILED = 10062
	//updateuserpassword
	ERR_UPDATE_ERROR                  = 10070
	ERR_UPDATE_MOBILE_TO_ALREADY_USED = 10071
	ERR_UPDATE_EMAIL_TO_ALREADY_USED  = 10072
	//oauth20
	ERR_GENERATE_QRCODE_ERROR       = 10080
	ERR_SAVE_QRCODE_ERROR           = 10081
	ERR_TEMPCODE_INVALID            = 10082
	ERR_CHECK_TEMPCODE_FAILED       = 10084
	ERR_TEMPCODE_INVALID_OR_EXPIRED = 10083
	ERR_TEMPCODE_WAIT_COMMIT        = 10085

	//corporation
	ERR_CORPORATION_CREATE_FAILED      = 10100
	ERR_CORPORATION_DUPLICATE          = 10101
	ERR_CORPORATION_ADD_USER_FAILED    = 10102
	ERR_CORPORATION_USER_DUPLICATE     = 10103
	ERR_CORPORATION_NOT_EXIST          = 10104
	ERR_CORPORATION_UPDATE_USER_FAILED = 10105
	ERR_CORPORATION_UPDATE_FAILED      = 10106
	ERR_USER_HAVE_NO_CORPORATION       = 10108

	//rbac
	ERR_PERMISSION_DENIED     = 11000
	ERR_PRIVILEGE_DUPLICATE   = 11001
	ERR_PRIVILEGE_NOT_EXIST   = 11005
	ERR_PRIVILEGE_SAVE_FAILED = 11002
	ERR_ROLE_SAVE_FAILED      = 11003
	ERR_ROLE_MAP_SAVE_FAILED  = 11004
	//rbac template
	ERR_ROLE_NOT_EXIST          = 11100
	ERR_TEMPLATE_ROLE_NOT_EXIST = 11101
)

const (
	VERIFYTYPE_PASSWORD   = 1
	VERIFYTYPE_MOBILE     = 2
	VERIFYTYPE_EMAIL      = 3
	VERIFYTYPE_COOKIE     = 4
	VERIFYTYPE_LOGINVCODE = 5

	NAMETYPE_ANY    = 0
	NAMETYPE_NAME   = 1
	NAMETYPE_MOBILE = 2
	NAMETYPE_EMAIL  = 3

	AUTH20ID_LOGIN_TYPE_WX = 1
	AUTH20ID_LOGIN_TYPE_QQ = 2
	AUTH20ID_LOGIN_TYPE_DD = 3
	AUTH20ID_LOGIN_TYPE_UW = 4

	AUTH20ID_TYPE_USERID       = 0
	AUTH20ID_TYPE_WX_OPENID    = 1
	AUTH20ID_TYPE_WX_UNIONID   = 2
	AUTH20ID_TYPE_QQ_OPENID    = 3
	AUTH20ID_TYPE_QQ_UNIONID   = 4
	AUTH20ID_TYPE_DING_OPENID  = 5
	AUTH20ID_TYPE_DING_UNIONID = 6

	VCODEADDRESSTYPE_MOBILE_LOGIN         = 1
	VCODEADDRESSTYPE_EMAIL_LOGIN          = 2
	VCODEADDRESSTYPE_MOBILE_REGISTER      = 3
	VCODEADDRESSTYPE_EMAIL_REGISTER       = 4
	VCODEADDRESSTYPE_MOBILE_PASSWORD      = 5
	VCODEADDRESSTYPE_EMAIL_PASSWORD       = 6
	VCODEADDRESSTYPE_SAFE_MOBILE_PASSWORD = 7 //打码手机号
	VCODEADDRESSTYPE_SAFE_EMAIL_PASSWORD  = 8 //打码邮箱

	UPDATE_PASSWORD_FIELD_CHECK_PERMISSION = 0 //检查更新权限
	UPDATE_PASSWORD_FIELD_PASSWORD         = 1 //更新密码
	UPDATE_PASSWORD_FIELD_MOBILE           = 2 //更新绑定手机
	UPDATE_PASSWORD_FIELD_EMAIL            = 3 //更新绑定邮箱
	UPDATE_PASSWORD_FIELD_MOBILE_UNBIND    = 4 //解除绑定手机
	UPDATE_PASSWORD_FIELD_EMAIL_UNBIND     = 5 //解除绑定邮箱

)
